version: "2"
services:
  backend:
    build: backend
    restart: unless-stopped
    ports:
      - "9012:8080"
    env_file:
      - ./backend/.env
  frontend:
    build: frontend
    restart: unless-stopped
    ports:
      - "9013:3000"
    depends_on:
      - backend
