version: "2"
services:
  backend:
    build: backend
    restart: unless-stopped
    ports:
      - 9019:8080
    env_file:
      - ./.env.backend
  frontend:
    build: frontend
    restart: unless-stopped
    ports:
      - 9020:3000
    depends_on:
      - backend
